program TrabinWeb;

uses
  IWStart,
  UTF8ContentParser,
  UserSessionUnit in 'src\controllers\UserSessionUnit.pas' {IWUserSession: TIWUserSessionBase},
  ServerController in 'src\controllers\ServerController.pas' {IWServerController: TIWServerControllerBase},
  uAtividade in 'src\views\uAtividade.pas' {F_Atividade: TIWAppForm},
  uCategoria in 'src\views\uCategoria.pas' {F_Categoria: TIWAppForm},
  uCodigoFiscal in 'src\views\uCodigoFiscal.pas' {F_CodigoFiscal: TIWAppForm},
  uConfiguracao in 'src\views\uConfiguracao.pas' {F_Configuracao: TIWAppForm},
  uCriaNota in 'src\views\uCriaNota.pas' {F_CriaNota: TIWAppForm},
  uLocalidade in 'src\views\uLocalidade.pas' {F_Localidade: TIWAppForm},
  uMain in 'src\views\uMain.pas' {F_Main: TIWAppForm},
  uNFeAutorizada in 'src\views\uNFeAutorizada.pas' {F_NFeAutorizada: TIWAppForm},
  uNFePendente in 'src\views\uNFePendente.pas' {F_NFePendente: TIWAppForm},
  uPessoa in 'src\views\uPessoa.pas' {F_Pessoa: TIWAppForm},
  uPlanoEstoque in 'src\views\uPlanoEstoque.pas' {F_PlanoEstoque: TIWAppForm},
  uContent.ListaAtividades in 'src\providers\uContent.ListaAtividades.pas',
  uContent.ListaAtividadesHelp in 'src\providers\uContent.ListaAtividadesHelp.pas',
  uContent.ListaBancosHelp in 'src\providers\uContent.ListaBancosHelp.pas',
  uContent.ListaCategorias in 'src\providers\uContent.ListaCategorias.pas',
  uContent.ListaClientesHelp in 'src\providers\uContent.ListaClientesHelp.pas',
  uContent.ListaCobrancasHelp in 'src\providers\uContent.ListaCobrancasHelp.pas',
  uContent.ListaCodigosFiscais in 'src\providers\uContent.ListaCodigosFiscais.pas',
  uContent.ListaCondicoesHelp in 'src\providers\uContent.ListaCondicoesHelp.pas',
  uContent.ListaLocalidades in 'src\providers\uContent.ListaLocalidades.pas',
  uContent.ListaLocalidadesHelp in 'src\providers\uContent.ListaLocalidadesHelp.pas',
  uContent.ListaNFeAutorizadas in 'src\providers\uContent.ListaNFeAutorizadas.pas',
  uContent.ListaNFePendentes in 'src\providers\uContent.ListaNFePendentes.pas',
  uContent.ListaNFePendentesItens in 'src\providers\uContent.ListaNFePendentesItens.pas',
  uContent.ListaNFePendentesParcelas in 'src\providers\uContent.ListaNFePendentesParcelas.pas',
  uContent.ListaPessoas in 'src\providers\uContent.ListaPessoas.pas',
  uContent.ListaPessoasHistoricos in 'src\providers\uContent.ListaPessoasHistoricos.pas',
  uContent.ListaPessoasObservacoes in 'src\providers\uContent.ListaPessoasObservacoes.pas',
  uContent.ListaPessoasParcelas in 'src\providers\uContent.ListaPessoasParcelas.pas',
  uContent.ListaPlanoEstoques in 'src\providers\uContent.ListaPlanoEstoques.pas',
  uContent.ListaRepresentantesHelp in 'src\providers\uContent.ListaRepresentantesHelp.pas',
  uContent.ListaTabelasHelp in 'src\providers\uContent.ListaTabelasHelp.pas',
  uContent.ListaOrcamentos in 'src\providers\uContent.ListaOrcamentos.pas',
  uOrcamento in 'src\views\uOrcamento.pas' {F_Orcamento: TIWAppForm},
  uContent.ListaOrcamentosCFOPS in 'src\providers\uContent.ListaOrcamentosCFOPS.pas',
  uContent.ListaOrcamentosItens in 'src\providers\uContent.ListaOrcamentosItens.pas',
  uContent.ListaOrcamentosParcelas in 'src\providers\uContent.ListaOrcamentosParcelas.pas',
  uOrcamentoItem in 'src\views\uOrcamentoItem.pas' {F_OrcamentoItem: TIWAppForm},
  uContent.ListaProdutosHelp in 'src\providers\uContent.ListaProdutosHelp.pas',
  uContent.ListaNotasFiscais in 'src\providers\uContent.ListaNotasFiscais.pas',
  uNotaFiscal in 'src\views\uNotaFiscal.pas' {F_NotaFiscal: TIWAppForm},
  uContent.ListaNotasFiscaisCFOPS in 'src\providers\uContent.ListaNotasFiscaisCFOPS.pas',
  uContent.ListaNotasFiscaisItens in 'src\providers\uContent.ListaNotasFiscaisItens.pas',
  uContent.ListaNotasFiscaisParcelas in 'src\providers\uContent.ListaNotasFiscaisParcelas.pas',
  uContent.ListaValidacoesHelp in 'src\providers\uContent.ListaValidacoesHelp.pas',
  uContent.ListaClassificacoesHelp in 'src\providers\uContent.ListaClassificacoesHelp.pas',
  uContent.ListaImportaOrcamentos in 'src\providers\uContent.ListaImportaOrcamentos.pas';

{$R *.res}

begin
  TIWStart.Execute(True);
end.
